apiVersion: kubeadm.k8s.io/v1beta1
kind: ClusterConfiguration
kubernetesVersion: stable
controlPlaneEndpoint: "172.20.141.98:16443"
networking:
  podSubnet: "192.168.0.0/16"
  dnsDomain: "cluster.local"
apiServer:
  certSANs:
  - oais-master01
  - oais-master02
  - oais-master03
  - 172.20.141.80
  - 172.20.141.84
  - 172.20.141.88
  - 172.20.141.98
  - 127.0.0.1
  extraArgs:
    authorization-mode: "Node,RBAC"
  timeoutForControlPlane: 4m0s
controllerManager:
  extraArgs:
    horizontal-pod-autoscaler-use-rest-clients: "true"
    horizontal-pod-autoscaler-sync-period: "10s"
    node-monitor-grace-period: "10s"
    experimental-cluster-signing-duration: "87600h"
certificatesDir: "/etc/kubernetes/pki"

