apiVersion: v1
kind: Service
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
spec:
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
  - name: https
    port: 443
    targetPort: 443
    protocol: TCP
  externalIPs:
  - 172.26.133.20
  - 172.26.133.21
  - 172.26.133.22
  - 172.26.133.23
  - 172.26.133.24
  - 172.26.133.25
  - 172.26.133.26
  - 172.26.133.27
  - 172.26.133.28
  selector:
    app: ingress-nginx
