apiVersion: v1
kind: Service
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
spec:
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
  - name: https
    port: 443
    targetPort: 443
    protocol: TCP
  externalIPs:
  - 172.20.141.98
  - 172.20.141.80
  - 172.20.141.84
  - 172.20.141.88
  selector:
    app: ingress-nginx
